# Generated by Django 5.2.2 on 2025-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_rename_variations_cartitem_variation'),
        ('store', '0005_rename_discription_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='store.variation'),
        ),
    ]
