# Generated by Django 5.2.2 on 2025-07-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_variation_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
