# Generated by Django 5.2.2 on 2025-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_rename_variations_cartitem_variation'),
        ('store', '0006_alter_variation_variation_category_productgallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
